server:
    port: 8080
    tomcat:
        max-threads: 50

#Actuator
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"
  metrics:
    se-global-registry: false
    export:
      prometheus:
        enabled: true # Whether exporting of metrics to Prometheus is enabled.
        step: 1m # Step size (i.e. reporting frequency) to use.